// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdsyjqengadsijidncfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkc3lqcWVuZ2Fkc2lqaWRuY2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODEwNDQsImV4cCI6MjA1ODY1NzA0NH0.PKKbdRlvZR9lPzw7XY1PlyvveSzJ2J8xFGgWzXxC19E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);